### ISSUE TITLE
milestone 0.5

### ISSUE THREAD

**Issue by wilf312** [wilf312/envsign#2]
- [ ] remove dist
- [ ] read external package.json
- [ ] add test
- [ ] **create cli tool**
- [ ] read package.json
- [ ] add label style
